### ISSUE TITLE
Screenshot for your readme?

### ISSUE THREAD

**Issue by PySimpleGUI** [Vresod/Among-Us-Editor-Python#7]
Hi!

You've got something so many Python programs don't have .... a graphical user interface!  Nothing grabs a repo's visitor's attention like a picture.  Posting a screenshot of your GUI would be GREAT to see!  I wanna know what it looks like and I'm sure others would enjoy it too.

They're super-easy to add.  I've got a video posted about how to do it using GitHub Issues if you're stumped.

Thank you very much for the kind mention in your readme.  Really appreciated!

 
![image](https://user-images.githubusercontent.com/46163555/143079175-28692dda-6716-4c81-a3c5-eeb3de17ac0d.png)

**Comment by Vresod** [comment]
added! thanks for the feedback
