### ISSUE TITLE
Newer version of PySimpleGUI, when released, frees you up from modifying a custom version

### ISSUE THREAD

**Issue by PySimpleGUI** [Vresod/Among-Us-Editor-Python#8]
I noticed you have PySimpleGUI.py in your project directly.  When I compared the differences between your version and the one on the PySimpleGUI github I see what you changed has been changed in version 4.55.1.4.  You should be able to use that version now and not have to modify it.

Once it's released to PyPI then you won't need a special version at all.

**Comment by Vresod** [comment]
Updated, thanks
